spring.application.name=tourisme

spring.profiles.active=dev

resilience4j.ratelimiter.instances.loginRateLimiter.limit-for-period=5
resilience4j.ratelimiter.instances.loginRateLimiter.limit-refresh-period=60s
resilience4j.ratelimiter.instances.loginRateLimiter.timeout-duration=0s

resilience4j.ratelimiter.instances.registerRateLimiter.limit-for-period=5
resilience4j.ratelimiter.instances.registerRateLimiter.limit-refresh-period=1800s
resilience4j.ratelimiter.instances.registerRateLimiter.timeout-duration=0s

resilience4j.ratelimiter.instances.refreshRateLimiter.limit-for-period=10
resilience4j.ratelimiter.instances.refreshRateLimiter.limit-refresh-period=3600s
resilience4j.ratelimiter.instances.refreshRateLimiter.timeout-duration=0s
