# PostgreSQL Database Configuration
    spring.datasource.url=jdbc:mysql://localhost:3306/cameroun_tour?createDatabaseIfNotExist=true
    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    spring.datasource.username=${DB_USER_MYSQL}
    spring.datasource.password=${DB_PASSWORD_MYSQL}

    spring.data.redis.repositories.enabled=false

# JPA Configuration
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
    spring.jpa.properties.hibernate.format_sql=true

# Mail (dev) - default to local SMTP (e.g. MailHog) to allow JavaMailSender autoconfiguration
    spring.mail.host=localhost
    spring.mail.port=1025
    spring.mail.username=
    spring.mail.password=
    spring.mail.properties.mail.smtp.auth=false
    spring.mail.properties.mail.smtp.starttls.enable=false

# logging.level.org.springframework=DEBUG

# --- Configuration JWT ---
    jwt.secret-key=kND+eAUJfgU5MGloND8N+42TjjMfVL+DOGdXgk1dLWv24ZCXUcUYSEtz1ZdCxjO6vO3MoEGKxQER72GDoqHvdA==
    jwt.access-token-expiration=900000  
    jwt.refresh-token-expiration=604800000
    # --- Noms des Cookies ---
    jwt.access-token.cookie-name=access_token
    jwt.refresh-token.cookie-name=refresh_token

# --- Configuration OAuth2 Client ---
app.oauth2.redirect-uri=http://localhost:3000/auth/callback

# --- OAuth2 Google ---
spring.security.oauth2.client.registration.google.client-id=VOTRE_CLIENT_ID.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=VOTRE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=openid, email, profile