spring.application.name=tourisme

spring.profiles.active=dev

# Springdoc OpenAPI / Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

resilience4j.ratelimiter.instances.loginRateLimiter.limit-for-period=5
resilience4j.ratelimiter.instances.loginRateLimiter.limit-refresh-period=60s
resilience4j.ratelimiter.instances.loginRateLimiter.timeout-duration=0s

resilience4j.ratelimiter.instances.registerRateLimiter.limit-for-period=5
resilience4j.ratelimiter.instances.registerRateLimiter.limit-refresh-period=1800s
resilience4j.ratelimiter.instances.registerRateLimiter.timeout-duration=0s

resilience4j.ratelimiter.instances.refreshRateLimiter.limit-for-period=10
resilience4j.ratelimiter.instances.refreshRateLimiter.limit-refresh-period=3600s
resilience4j.ratelimiter.instances.refreshRateLimiter.timeout-duration=0s

# Rate limiter pour les requêtes OTP (envoi, vérification, reset password)
resilience4j.ratelimiter.instances.otpRateLimiter.limit-for-period=3
resilience4j.ratelimiter.instances.otpRateLimiter.limit-refresh-period=60s
resilience4j.ratelimiter.instances.otpRateLimiter.timeout-duration=0s

logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR
